<?php

return [
    'allow_type' => [
        'image/jpg',
        'image/jpeg',
        'image/png',
        'image/gif',
        'image/webp',
        'application/pdf',
        'application/vnd.ms-excel',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.ms-powerpoint',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'text/plain',
        'text/csv',
        'application/csv',
        'application/zip',
        'application/x-7z-compressed',
        'application/x-rar',
        'application/octet-stream',
        'audio/mpeg',
        'audio/wav',
        'audio/ogg',
        'video/mp4',
        'video/webm',
        'video/quicktime',
    ],
    'not_allow_ext' => [
        'js',
        'php',
        'exe',
        'sh',
        'py',
        'css',
        'html',
        'htm',
        'xml',
        'bat',
    ],
    'max_file_size' => env('UPLOAD_MAX_FILE_SIZE', 100 * 1024 * 1024),
];
