[program:antifraud-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/service-antifraud/www/service.antifraud.local.com/artisan queue:work --tries=3 --timeout=300 --sleep=3
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=laradock
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/service-antifraud/www/service.antifraud.local.com/storage/logs/worker.log
stopwaitsecs=360
